use_frameworks!

target 'SwiftyEventBus_Example' do
  pod 'SwiftyEventBus', :path => '../'

  target 'SwiftyEventBus_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
