osx_image: xcode10.2
language: objective-c
before_install: true
install: true
cache: cocoapods
podfile: Podfile
xcode_scheme: SwiftyEventBus
xcode_workspace: SwiftyEventBus.xcworkspace
env:
  global:
  - FRAMEWORK_NAME=SwiftyEventBus
before_install:
- gem install cocoapods -v '1.7.4'
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage update
- pod install
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace SwiftyEventBus.xcworkspace -scheme SwiftyEventBus -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2'
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 05bd0885-f6ff-4e7a-b774-14ca8ea4badf
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: DjIQDHMOxg1ztrIG84hUTYPUjcTJr1l1PUf606oalFcWM2q2MS74nYfPEWkXd3dgUfiiyfnXDQBi9vh6jIdBd4fnvBMZ7/oqqr/fjkXvVzTNk8aay7I9g6kuI/oKShmkG++st+e9+2SOcLPrEJLN8JT8bi9X6IqtNCOMNYC51rJp4+ji5ej+fn8+SmVuO/CvBwtkRJXV96doVY4rJgBv4q6SdZMjS29N603cstr9YEi4tCKqZn6veBvWvohE1SjCfL2GPHFhKYps6/t65l9lIR3kIauLVTLxHD/hQq4SfKNVMhf+aR1LrQSae/R5K5Eo4p3KLXT3MLYsSEnG2ZE22dI8TEh8o+TtAwDP6kSK55QVmouZVTFUs4HbuAeuYrly5jAFrNlzc8LSF1Ej+SLGD0+/stQ7w60gkQAoiB8h0rFm+Pa2F5fFM1nUOkAme8xhoeR3aILg5E+gUCBXmUN3CwvKcPRMTZ341lNOqC3vb+vmRepP+1WZpfORNTbiDEhZYpaW0GPyuy1feEWmt/zVqG/X9kKCTaw4bQ9mmxQFdvPo4QwwxDTp62ReNTehboO3ybXbpPnwT/UTX8PwrJi41ojR1wETPEdsPQnuu0wQO/mYgAGcB0olq+ySool6qcSx7s3iTINEIRpR0XtugEC7uLjWPjl08L06b9SD+JY5Ibs=
  file: SwiftyEventBus.framework.zip
  on:
    repo: Maru-zhang/SwiftyEventBus
    branch: develop
